# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
   push:
    branches:
    - master

jobs:
   build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: dependecy install and build
      run: |
       mvn clean install
       mvn package
    - uses: docker/login-action@v2
      with:
       username: markodjordjevic244
       password: Novasifra123
    - name: build and push
      run: |
       docker build -t myApp .
       docker push myApp 
       

