# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
   push:
    branches:
    - master

jobs:
   build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: dependecy install and build
      run: |
       mvn clean install
       mvn package
    - uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1
    - name: login to ecr
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: build and push
      run: |
       docker build -t markodj .
       docker tag markodj:latest public.ecr.aws/k9r4x3e0/markodj:latest
       docker push public.ecr.aws/k9r4x3e0/markodj:latest

       
       
       
       
       

